#! /bin/sh

#:::::::::::::::::::::::::::::::
#   ┏━┓┏━┓┏━┓╻  ╻┏┓┏┓┏━┓┏━╸   ::
#   ┃━┃┗━┓┃━╹┃┏┓┃┃┗┛┃┣┳┛┃     ::
#   ┗━┛┗━┛╹  ┗┛┗┛╹  ╹╹┗╸┗━╸   :: 
#  by: asarch                 :: 
#:::::::::::::::::::::::::::::::

#::::::::::::::::::::::::::::::::::::::::::::::::::
#                                                ::
#                 General settings               ::
#                                                ::
#::::::::::::::::::::::::::::::::::::::::::::::::::

sxhkd &
compton &
nm-applet & 
#megasync &
[ !  -s ~/.config/mpd/pid ] && mpd & 
# Solve problem Java with Netbeans and Pycharm
wmname LG3D &
# Keyboard to abnt2
setxkbmap br &
# Launch polybar
$HOME/.config/polybar/launch.sh &

# Launch tint2
#tint2 &

# Connect secondary monitor and auto adjust your resolution
$HOME/scripts/autoHDMI.sh &

# Set Random Wallpaper 
$HOME/scripts/random-wall.sh &

# Set Wallpaper
# feh --randomize --bg-fill /home/marco/Imagens/wallpaper\ Arch\ Linux\ 2017/*

# Desktops
bspc monitor --reset-desktops term www dev play chat text git virt 

# Make windows float on specific desktops
# https://github.com/baskerville/bspwm/issues/325
bspc subscribe node_manage | while read event monitor desktop nodeid ipid; do
    case "$desktop" in
        (www|play|chat|term|git|virt|dev|text)
            bspc node "$nodeid" --state floating
            ;;
    esac
done &

#::::::::::::::::::::::::::::::::::::::::::::::::::
#                                                ::
#                  Visual settings               ::
#                                                ::
#::::::::::::::::::::::::::::::::::::::::::::::::::
bspc config border_width                1
bspc config window_gap                  10
bspc config top_padding                 14 
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config auto_alternate              true
bspc config auto_cancel                 true
bspc config focus_by_distance           true
bspc config history_aware_focus         true
bspc config center_pseudo_tiled         true
bspc config normal_border_color         "#131313"
bspc config focused_border_color        "#829091"
bspc config presel_border_color         "#95A2A3"
bspc config urgent_border_color         "#0FC962"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1



#::::::::::::::::::::::::::::::::::::::::::::::::::
#                                                ::
#                       Rules                    ::
#                                                ::
#::::::::::::::::::::::::::::::::::::::::::::::::::
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Nautilus pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Steam floating=on
bspc rule -a feh floating=on manage=off
bspc rule -a nomacs manage=off follow=on

# Send to www desktop
bspc rule --add Firefox desktop='www' follow=on

# Send to term desktop
bspc rule --add Subl3 desktop='term' follow=on

#bspc rule --add Tilix desktop='term' state=floating follow=on
#bspc rule --add Urxvt desktop='term' follow=on

# Send to dev desktop
bspc rule --add PyCharm desktop='dev' follow=on
bspc rule --add NetBeans desktop='dev' follow=on
bspc rule --add Subl3 desktop='dev' follow=on

# Send to chat desktop
bspc rule --add Weechat desktop='chat' --one-shot follow=on
bspc rule --add Skype desktop='chat' --one-shot follow=on
bspc rule --add TelegramDesktop desktop='chat' follow=on

# Send to play desktop
bspc rule --add Vlc desktop='play' follow=on
bspc rule --add Spotify desktop='play' follow=on
bspc rule --add Stremio desktop='play' follow=on

# Send to git desktop
bspc rule --add GitKraken desktop='git' follow=on

# Send to Virt desktop
bspc rule --add VirtualBox desktop='virt' follow=on
bspc rule --add Genymotion desktop='virt' follow=on

# other floating windows
bspc rule --add Eog state=floating
bspc rule --add megasync state=floating
